### ISSUE TITLE
Regarding PlayButtonFromSearch

### ISSUE THREAD

**Issue by Neeraj029** [the-woofs/woof-music#1]
Henloo 
So I was taking a look at the code and trying this app, cannot we just play the music straightaway when the user clicks PlayButtonFromSearch?
![image](https://user-images.githubusercontent.com/66945520/156764504-8456bdc8-ebc7-43d5-9c80-289063d7a808.png)

**Comment by ACuteWoof** [comment]
Oh well you can create a player that does that but I have this as a separate component for organizing the project. The player is located at the [bottom bar where the album art is shown](https://github.com/the-woofs/woof-music/blob/main/src/Components/CurrentlyPlayingInfo/index.jsx) so like the button has to change a few hooks of MainScreen which then transfers them to the player. The player depends on other component's for controls so playing it straight on the button wouldn't be intuitive.

**Comment by Neeraj029** [comment]
Hmm oki :thinking:
